framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    php_errors:
        log: true

when@test:
    framework:
        test: true
