version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - .:/srv
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory 
      #  from the bind-mount for better performance by enabling the next line:
      - /srv/vendor
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/public:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5451
        protocol: tcp
        
#  database_test:
#    image: postgres:${POSTGRES_VERSION:-14}-alpine
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
#      - POSTGRES_USER=${POSTGRES_USER:-app}
#    volumes:
#      - db_data_test:/var/lib/postgresql/data:rw
#    ports:
#      - target: 5432
#        published: 5433
#        protocol: tcp
###< doctrine/doctrine-bundle ###
  
  moco_test:
    build:
      context: docker/moco
    volumes:
      - ./tests/resources/moco/test/:/var/moco:ro
  
  moco_int:
    build:
      context: docker/moco
    volumes:
      - ./tests/resources/moco/int/:/var/moco:ro

  newman:
    build:
      context: docker/newman
    volumes:
      - ./tests/integration:/etc/newman:ro

volumes:
###> doctrine/doctrine-bundle ###
  db_data_test:
###< doctrine/doctrine-bundle ###
