version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
    environment:
      APP_ENV: dev
    depends_on:
      - database_test

  pwa:
    build:
      context: ./pwa
      target: api_platform_pwa_dev
    volumes:
      - ./pwa:/usr/src/pwa:rw,cached

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5451
        protocol: tcp
        
  database_test:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-api}
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-api-platform}
    volumes:
      - db_data_test:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
###< doctrine/doctrine-bundle ###

  newman:
    build:
      context: api/docker/newman
    volumes:
      - ./api/tests/integration:/etc/newman:ro

volumes:
###> doctrine/doctrine-bundle ###
  db_data_test:
###< doctrine/doctrine-bundle ###
