<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240921151135 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Alter tables after Doctrine update';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE action_log ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN action_log.id IS \'\'');
        $this->addSql('ALTER TABLE catch_state ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN catch_state.id IS \'\'');
        $this->addSql('ALTER TABLE category_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN category_form.id IS \'\'');
        $this->addSql('ALTER TABLE dex ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE dex ALTER region_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dex.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN dex.region_id IS \'\'');
        $this->addSql('ALTER TABLE dex_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE dex_availability ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE dex_availability ALTER dex_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dex_availability.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN dex_availability.pokemon_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN dex_availability.dex_id IS \'\'');
        $this->addSql('ALTER TABLE game ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game ALTER bundle_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game.bundle_id IS \'\'');
        $this->addSql('ALTER TABLE game_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_availability ALTER game_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_availability.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_availability.game_id IS \'\'');
        $this->addSql('ALTER TABLE game_bundle ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle ALTER generation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_bundle.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_bundle.generation_id IS \'\'');
        $this->addSql('ALTER TABLE game_bundle_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_availability ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_availability ALTER bundle_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_bundle_availability.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_availability.pokemon_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_availability.bundle_id IS \'\'');
        $this->addSql('ALTER TABLE game_bundle_shiny_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_shiny_availability ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_shiny_availability ALTER bundle_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_bundle_shiny_availability.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_shiny_availability.pokemon_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_shiny_availability.bundle_id IS \'\'');
        $this->addSql('ALTER TABLE game_generation ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_generation.id IS \'\'');
        $this->addSql('ALTER TABLE game_shiny_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_shiny_availability ALTER game_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_shiny_availability.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN game_shiny_availability.game_id IS \'\'');
        $this->addSql('ALTER TABLE pokedex ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE pokedex ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE pokedex ALTER trainer_dex_id TYPE UUID');
        $this->addSql('ALTER TABLE pokedex ALTER catch_state_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN pokedex.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokedex.pokemon_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokedex.trainer_dex_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokedex.catch_state_id IS \'\'');
        $this->addSql('ALTER TABLE pokemon ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER original_game_bundle_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER variant_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER regional_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER special_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER category_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER primary_type_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER secondary_type_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN pokemon.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.original_game_bundle_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.variant_form_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.regional_form_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.special_form_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.category_form_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.primary_type_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon.secondary_type_id IS \'\'');
        $this->addSql('ALTER TABLE pokemon_availabilities ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon_availabilities ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon_availabilities ALTER items TYPE TEXT');
        $this->addSql('COMMENT ON COLUMN pokemon_availabilities.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon_availabilities.pokemon_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN pokemon_availabilities.items IS \'\'');
        $this->addSql('ALTER TABLE region ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN region.id IS \'\'');
        $this->addSql('ALTER TABLE regional_dex_number ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE regional_dex_number ALTER region_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN regional_dex_number.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN regional_dex_number.region_id IS \'\'');
        $this->addSql('ALTER TABLE regional_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN regional_form.id IS \'\'');
        $this->addSql('ALTER TABLE special_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN special_form.id IS \'\'');
        $this->addSql('ALTER TABLE trainer_dex ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE trainer_dex ALTER dex_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN trainer_dex.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN trainer_dex.dex_id IS \'\'');
        $this->addSql('ALTER TABLE type ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN type.id IS \'\'');
        $this->addSql('ALTER TABLE variant_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN variant_form.id IS \'\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE region ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN region.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE regional_dex_number ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE regional_dex_number ALTER region_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN regional_dex_number.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN regional_dex_number.region_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE catch_state ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN catch_state.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pokemon ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER original_game_bundle_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER variant_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER regional_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER special_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER category_form_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER primary_type_id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon ALTER secondary_type_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN pokemon.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.original_game_bundle_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.variant_form_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.regional_form_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.special_form_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.category_form_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.primary_type_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.secondary_type_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE type ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN type.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE trainer_dex ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE trainer_dex ALTER dex_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN trainer_dex.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN trainer_dex.dex_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE action_log ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN action_log.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pokemon_availabilities ALTER items TYPE TEXT');
        $this->addSql('ALTER TABLE pokemon_availabilities ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE pokemon_availabilities ALTER pokemon_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN pokemon_availabilities.items IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN pokemon_availabilities.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokemon_availabilities.pokemon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE dex ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE dex ALTER region_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dex.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dex.region_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE game_bundle ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle ALTER generation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_bundle.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_bundle.generation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE variant_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN variant_form.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE special_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN special_form.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE regional_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN regional_form.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE dex_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE dex_availability ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE dex_availability ALTER dex_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dex_availability.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dex_availability.pokemon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dex_availability.dex_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE game ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game ALTER bundle_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game.bundle_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE category_form ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN category_form.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE game_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_availability ALTER game_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_availability.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_availability.game_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE game_generation ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_generation.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE game_bundle_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_availability ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_availability ALTER bundle_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_bundle_availability.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_availability.pokemon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_availability.bundle_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE game_bundle_shiny_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_shiny_availability ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE game_bundle_shiny_availability ALTER bundle_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_bundle_shiny_availability.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_shiny_availability.pokemon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_bundle_shiny_availability.bundle_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE game_shiny_availability ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE game_shiny_availability ALTER game_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN game_shiny_availability.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN game_shiny_availability.game_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pokedex ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE pokedex ALTER pokemon_id TYPE UUID');
        $this->addSql('ALTER TABLE pokedex ALTER trainer_dex_id TYPE UUID');
        $this->addSql('ALTER TABLE pokedex ALTER catch_state_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN pokedex.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokedex.pokemon_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokedex.trainer_dex_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pokedex.catch_state_id IS \'(DC2Type:uuid)\'');
    }
}
