<?php

declare(strict_types=1);

namespace App\Tests\Functional\Controller;

/**
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class DexControllerTestData
{
    /**
     * @return string[][]|bool[][]
     */
    public static function getUser12Content(): array
    {
        return [
            [
                'dex_slug' => 'redgreenblueyellow',
                'name' => 'Red / Green / Blue / Yellow',
                'french_name' => 'Rouge / Vert / Bleu / Jaune',
                'slug' => 'redgreenblueyellow',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemerald',
                'name' => 'Ruby / Sapphire / Emerald',
                'french_name' => 'Rubis / Saphir / Émeraude',
                'slug' => 'rubysapphireemerald',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'home',
                'name' => 'Home',
                'french_name' => 'Home',
                'slug' => 'home',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homeshiny',
                'name' => 'Home Shiny',
                'french_name' => 'Home Chromatique',
                'slug' => 'home_shiny',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homeshiny',
                'name' => 'Home Shiny OT',
                'french_name' => 'Home Chromatique OT',
                'slug' => 'homeshinyot',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo',
                'french_name' => 'Home PoGo',
                'slug' => 'home_pogo',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => true,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo OT',
                'french_name' => 'Home PoGo OT',
                'slug' => 'homepogoot',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => true,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo Poké Ball',
                'french_name' => 'Home PoGo Poké Ball',
                'slug' => 'homepogopokeball',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => true,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemeraldshiny',
                'name' => 'Ruby / Sapphire / Emerald: Shiny',
                'french_name' => 'Rubis / Saphir / Émeraude: Chromatique',
                'slug' => 'rubysapphireemeraldshiny',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
        ];
    }

    /**
     * @return string[][]|bool[][]
     */
    public static function getUser12ContentWithUnreleased(): array
    {
        return [
            [
                'dex_slug' => 'redgreenblueyellow',
                'name' => 'Red / Green / Blue / Yellow',
                'french_name' => 'Rouge / Vert / Bleu / Jaune',
                'slug' => 'redgreenblueyellow',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'goldsilvercrystal',
                'name' => 'Gold / Silver / Crystal',
                'french_name' => 'Or / Argent / Cristal',
                'slug' => 'goldsilvercrystal',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => false,
            ],
            [
                'dex_slug' => 'rubysapphireemerald',
                'name' => 'Ruby / Sapphire / Emerald',
                'french_name' => 'Rubis / Saphir / Émeraude',
                'slug' => 'rubysapphireemerald',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'home',
                'name' => 'Home',
                'french_name' => 'Home',
                'slug' => 'home',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homeshiny',
                'name' => 'Home Shiny',
                'french_name' => 'Home Chromatique',
                'slug' => 'home_shiny',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homeshiny',
                'name' => 'Home Shiny OT',
                'french_name' => 'Home Chromatique OT',
                'slug' => 'homeshinyot',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo',
                'french_name' => 'Home PoGo',
                'slug' => 'home_pogo',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => true,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo OT',
                'french_name' => 'Home PoGo OT',
                'slug' => 'homepogoot',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => true,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo Poké Ball',
                'french_name' => 'Home PoGo Poké Ball',
                'slug' => 'homepogopokeball',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => true,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemeraldshiny',
                'name' => 'Ruby / Sapphire / Emerald: Shiny',
                'french_name' => 'Rubis / Saphir / Émeraude: Chromatique',
                'slug' => 'rubysapphireemeraldshiny',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
        ];
    }

    /**
     * @return string[][]|bool[][]
     */
    public static function getUser13Content(): array
    {
        return [
            [
                'dex_slug' => 'redgreenblueyellow',
                'name' => 'Red / Green / Blue / Yellow',
                'french_name' => 'Rouge / Vert / Bleu / Jaune',
                'slug' => 'redgreenblueyellow',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemerald',
                'name' => 'Ruby / Sapphire / Emerald',
                'french_name' => 'Rubis / Saphir / Émeraude',
                'slug' => 'rubysapphireemerald',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'home',
                'name' => 'Home',
                'french_name' => 'Home',
                'slug' => 'home',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homeshiny',
                'name' => 'Home Shiny',
                'french_name' => 'Home Chromatique',
                'slug' => 'homeshiny',
                'is_shiny' => true,
                'is_private' => false,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo',
                'french_name' => 'Home PoGo',
                'slug' => 'homepogo',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemeraldshiny',
                'name' => 'Ruby / Sapphire / Emerald: Shiny',
                'french_name' => 'Rubis / Saphir / Émeraude: Chromatique',
                'slug' => 'rubysapphireemeraldshiny',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
        ];
    }

    /**
     * @return string[][]|bool[][]
     */
    public static function getUserUnknownContent(): array
    {
        return [
            [
                'dex_slug' => 'redgreenblueyellow',
                'name' => 'Red / Green / Blue / Yellow',
                'french_name' => 'Rouge / Vert / Bleu / Jaune',
                'slug' => 'redgreenblueyellow',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemerald',
                'name' => 'Ruby / Sapphire / Emerald',
                'french_name' => 'Rubis / Saphir / Émeraude',
                'slug' => 'rubysapphireemerald',
                'is_shiny' => false,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'home',
                'name' => 'Home',
                'french_name' => 'Home',
                'slug' => 'home',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homeshiny',
                'name' => 'Home Shiny',
                'french_name' => 'Home Chromatique',
                'slug' => 'homeshiny',
                'is_shiny' => true,
                'is_private' => false,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'homepogo',
                'name' => 'Home PoGo',
                'french_name' => 'Home PoGo',
                'slug' => 'homepogo',
                'is_shiny' => false,
                'is_private' => false,
                'is_display_form' => false,
                'display_template' => 'list-7',
                'is_on_home' => false,
                'is_released' => true,
            ],
            [
                'dex_slug' => 'rubysapphireemeraldshiny',
                'name' => 'Ruby / Sapphire / Emerald: Shiny',
                'french_name' => 'Rubis / Saphir / Émeraude: Chromatique',
                'slug' => 'rubysapphireemeraldshiny',
                'is_shiny' => true,
                'is_private' => true,
                'is_display_form' => true,
                'display_template' => 'box',
                'is_on_home' => false,
                'is_released' => true,
            ],
        ];
    }
}
