<?php

namespace App\Tests\Functionnal\Api;

final class AlbumApiTestData
{
    /**
     * @return string[][]|null[][]
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public static function getExpectedRegGreenBlueYellowContent(): array
    {
        return [
            [
                'pokemon_slug' => 'bulbasaur',
                'pokemon_name' => 'Bulbasaur',
                'pokemon_simplified_name' => 'Bulbasaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Bulbizarre',
                'pokemon_simplified_french_name' => 'Bulbizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'bulbasaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'ivysaur',
                'pokemon_name' => 'Ivysaur',
                'pokemon_simplified_name' => 'Ivysaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Herbizarre',
                'pokemon_simplified_french_name' => 'Herbizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'ivysaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'maybe',
                'catch_state_name' => 'Maybe',
                'catch_state_french_name' => 'Peut être',
            ],
            [
                'pokemon_slug' => 'venusaur',
                'pokemon_name' => 'Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'maybenot',
                'catch_state_name' => 'Maybe not',
                'catch_state_french_name' => 'Peut être pas',
            ],
            [
                'pokemon_slug' => 'caterpie',
                'pokemon_name' => 'Caterpie',
                'pokemon_simplified_name' => 'Caterpie',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Chenipan',
                'pokemon_simplified_french_name' => 'Chenipan',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'caterpie',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'maybenot',
                'catch_state_name' => 'Maybe not',
                'catch_state_french_name' => 'Peut être pas',
            ],
            [
                'pokemon_slug' => 'metapod',
                'pokemon_name' => 'Metapod',
                'pokemon_simplified_name' => 'Metapod',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Chrysacier',
                'pokemon_simplified_french_name' => 'Chrysacier',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'metapod',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree',
                'pokemon_name' => 'Butterfree',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'butterfree',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'douze',
                'pokemon_name' => 'Douze',
                'pokemon_simplified_name' => 'Douze',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Douze',
                'pokemon_simplified_french_name' => 'Douze',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'douze',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
        ];
    }

    /**
     * @return string[][]|null[][]
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public static function getExpectedHomeContent(): array
    {
        return [
            [
                'pokemon_slug' => 'bulbasaur',
                'pokemon_name' => 'Bulbasaur',
                'pokemon_simplified_name' => 'Bulbasaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Bulbizarre',
                'pokemon_simplified_french_name' => 'Bulbizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'bulbasaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'ivysaur',
                'pokemon_name' => 'Ivysaur',
                'pokemon_simplified_name' => 'Ivysaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Herbizarre',
                'pokemon_simplified_french_name' => 'Herbizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'ivysaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'venusaur',
                'pokemon_name' => 'Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'venusaur-f',
                'pokemon_name' => 'Venusaur ♀',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => '♀️',
                'pokemon_french_name' => 'Florizarre ♀',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => '♀️',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => 'gender',
                'variant_form_name' => 'Gender',
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'venusaur-mega',
                'pokemon_name' => 'Mega Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => 'Mega',
                'pokemon_french_name' => 'Mega Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => 'Mega',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => 'mega',
                'special_form_name' => 'Mega',
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'venusaur-gmax',
                'pokemon_name' => 'Gigantamax Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => 'Gigantamax',
                'pokemon_french_name' => 'Gigamax Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => 'Gigamax',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => 'gigantamax',
                'special_form_name' => 'Gigantamax',
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => 'no',
                'catch_state_name' => 'No',
                'catch_state_french_name' => 'Non',
            ],
            [
                'pokemon_slug' => 'caterpie',
                'pokemon_name' => 'Caterpie',
                'pokemon_simplified_name' => 'Caterpie',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Chenipan',
                'pokemon_simplified_french_name' => 'Chenipan',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'caterpie',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'metapod',
                'pokemon_name' => 'Metapod',
                'pokemon_simplified_name' => 'Metapod',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Chrysacier',
                'pokemon_simplified_french_name' => 'Chrysacier',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'metapod',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree',
                'pokemon_name' => 'Butterfree',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'butterfree',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree-f',
                'pokemon_name' => 'Butterfree ♀',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => '♀️',
                'pokemon_french_name' => 'Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => '♀️',
                'pokemon_icon' => 'butterfree',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => 'gender',
                'variant_form_name' => 'Gender',
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree-gmax',
                'pokemon_name' => 'Gigantamax Butterfree',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => 'Gigantamax',
                'pokemon_french_name' => 'Gigamax Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => 'Gigamax',
                'pokemon_icon' => 'butterfree-gmax',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => 'gigantamax',
                'special_form_name' => 'Gigantamax',
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'douze',
                'pokemon_name' => 'Douze',
                'pokemon_simplified_name' => 'Douze',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Douze',
                'pokemon_simplified_french_name' => 'Douze',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'douze',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
        ];
    }

    /**
     * @return string[][]|null[][]
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public static function getExpectedHomeShinyContent(): array
    {
        return [
            [
                'pokemon_slug' => 'bulbasaur',
                'pokemon_name' => 'Bulbasaur',
                'pokemon_simplified_name' => 'Bulbasaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Bulbizarre',
                'pokemon_simplified_french_name' => 'Bulbizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'bulbasaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'ivysaur',
                'pokemon_name' => 'Ivysaur',
                'pokemon_simplified_name' => 'Ivysaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Herbizarre',
                'pokemon_simplified_french_name' => 'Herbizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'ivysaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'venusaur',
                'pokemon_name' => 'Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'venusaur-f',
                'pokemon_name' => 'Venusaur ♀',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => '♀️',
                'pokemon_french_name' => 'Florizarre ♀',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => '♀️',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => 'gender',
                'variant_form_name' => 'Gender',
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'venusaur-mega',
                'pokemon_name' => 'Mega Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => 'Mega',
                'pokemon_french_name' => 'Mega Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => 'Mega',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => 'mega',
                'special_form_name' => 'Mega',
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'venusaur-gmax',
                'pokemon_name' => 'Gigantamax Venusaur',
                'pokemon_simplified_name' => 'Venusaur',
                'pokemon_forms_label' => 'Gigantamax',
                'pokemon_french_name' => 'Gigamax Florizarre',
                'pokemon_simplified_french_name' => 'Florizarre',
                'pokemon_forms_french_label' => 'Gigamax',
                'pokemon_icon' => 'venusaur',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => 'gigantamax',
                'special_form_name' => 'Gigantamax',
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'caterpie',
                'pokemon_name' => 'Caterpie',
                'pokemon_simplified_name' => 'Caterpie',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Chenipan',
                'pokemon_simplified_french_name' => 'Chenipan',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'caterpie',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'metapod',
                'pokemon_name' => 'Metapod',
                'pokemon_simplified_name' => 'Metapod',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Chrysacier',
                'pokemon_simplified_french_name' => 'Chrysacier',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'metapod',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree',
                'pokemon_name' => 'Butterfree',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => '',
                'pokemon_french_name' => 'Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => '',
                'pokemon_icon' => 'butterfree',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree-f',
                'pokemon_name' => 'Butterfree ♀',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => '♀️',
                'pokemon_french_name' => 'Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => '♀️',
                'pokemon_icon' => 'butterfree',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => null,
                'special_form_name' => null,
                'variant_form_slug' => 'gender',
                'variant_form_name' => 'Gender',
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
            [
                'pokemon_slug' => 'butterfree-gmax',
                'pokemon_name' => 'Gigantamax Butterfree',
                'pokemon_simplified_name' => 'Butterfree',
                'pokemon_forms_label' => 'Gigantamax',
                'pokemon_french_name' => 'Gigamax Papilusion',
                'pokemon_simplified_french_name' => 'Papilusion',
                'pokemon_forms_french_label' => 'Gigamax',
                'pokemon_icon' => 'butterfree-gmax',
                'regional_form_slug' => null,
                'regional_form_name' => null,
                'special_form_slug' => 'gigantamax',
                'special_form_name' => 'Gigantamax',
                'variant_form_slug' => null,
                'variant_form_name' => null,
                'catch_state_slug' => null,
                'catch_state_name' => null,
                'catch_state_french_name' => null,
            ],
        ];
    }
}
