services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $spreadsheetId: '%env(SPREADSHEET_ID)%'
            string $googleApiSheetsUrl: '%env(GOOGLE_API_SHEETS_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
