services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $spreadsheetId: '%env(SPREADSHEET_ID)%'
            string $googleApiSheetsUrl: '%env(GOOGLE_API_SHEETS_URL)%'
            int $eloKFactor: '%env(ELO_K_FACTOR)%'
            int $eloDDifference: '%env(ELO_D_DIFFERENCE)%'
            int $eloDefault: '%env(ELO_DEFAULT)%'
            string $sqlDir: '%kernel.project_dir%/resources/sql'
            
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
